In [13]:
import numpy as np

1

In [14]:
ar = np.zeros(10)
ar[4] = 1
ar

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2

In [15]:
ar = np.arange(10, 50)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3

In [16]:
ar = np.array(sorted(ar, reverse=True))
ar

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4

In [17]:
matrix = np.arange(0, 9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5

In [18]:
ar.nonzero()[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39], dtype=int64)

6

In [19]:
id_matrix = np.eye(3)
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7

In [20]:
random_matrix = np.random.rand(3,3)
random_matrix

array([[0.28471844, 0.30767303, 0.85179771],
       [0.01031149, 0.23472501, 0.88184316],
       [0.69337666, 0.79244113, 0.10394267]])

8

In [21]:
random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
normalized_matrix

array([[0.25519565, 0.67775094, 0.99929579, 1.        , 0.19829561],
       [0.51155069, 0.93647295, 0.06206583, 0.50770831, 0.71092969],
       [0.61792554, 0.54753363, 0.18917957, 0.68988311, 0.91287692],
       [0.04168447, 0.43561799, 0.89173892, 0.34889445, 0.        ],
       [0.06584135, 0.13286328, 0.78322968, 0.90624046, 0.19773329]])

9

In [22]:
array = np.array([1, 3, 5, 11, 15, 20, 25])
target = 14
closest_value = array[np.abs(array - target).argmin()]
closest_value

15

10

In [23]:
id_matrix
for i in range(id_matrix.shape[0]):
    maxi = np.argmax(id_matrix[i])
    id_matrix[i, maxi] = 0

11

In [24]:
array = np.array([2, 3, 2, 5, 8, 3, 3, 7, 2, 3, 5, 5, 5, 5])
most_common = np.bincount(array).argmax()
most_common

5

12

In [25]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_product = np.dot(array, array.T)
matrix_product

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

13

In [26]:
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
determinant = np.linalg.det(matrix)
determinant

-306.0

14

In [27]:
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
try:
    inverse_matrix = np.linalg.inv(matrix)
except np.linalg.LinAlgError:
    inverse_matrix = "Matrix is singular and cannot be inverted."
inverse_matrix

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])