In [62]:
import numpy as np

1

In [ ]:
ar = np.zeros(10)
ar[4] = 1
ar

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2

In [64]:
ar = np.arange(10, 50)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3

In [65]:
ar = np.array(sorted(ar, reverse=True))
ar

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4

In [66]:
matrix = np.arange(0, 9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5

In [67]:
ar.nonzero()[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39], dtype=int64)

6

In [68]:
id_matrix = np.eye(3)
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7

In [69]:
random_matrix = np.random.rand(3,3)
random_matrix

array([[0.84651154, 0.76225998, 0.70669833],
       [0.41718781, 0.33631133, 0.30062402],
       [0.45159191, 0.64943966, 0.65177631]])

8

9

In [70]:
n = 25.5
closest_value = ar[np.abs(ar-n).argmin()]
closest_value

26

10

In [71]:
id_matrix
for i in range(id_matrix.shape[0]):
    maxi = np.argmax(id_matrix[i])
    id_matrix[i, maxi] = 0

11

12

13

14